vqgan_ckpt: ??? 

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: ???
diffusion_depth_size: ???
diffusion_num_channels: ???
dim_mults: ???
results_folder: ./outputs/ddpm2/
results_folder_postfix: 'gnks'
load_milestone: False

batch_size: 40
num_workers: 20
logger: wandb
objective: pred_x0
save_and_sample_every: 1000
denoising_fn: Unet3D
train_lr: 5e-5
timesteps: 60 # number of steps
sampling_timesteps: 50 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 700000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: 1

